feat: add more branch checks

diff --git a/.github/workflows/check-branch.yml b/.github/workflows/check-branch.yml
--- a/.github/workflows/check-branch.yml
+++ b/.github/workflows/check-branch.yml
@@ -12,9 +12,20 @@ jobs:
         uses: thollander/actions-comment-pull-request@v2
         with:
           message: |
-            We regret to inform you that you are currently not able to merge your changes into the main branch due to restrictions applied by our SRE team. To proceed with merging your changes, we kindly request that you create a pull request from the next branch. Our team will then review the changes and work with you to ensure a successful merge into the main branch.
+            We regret to inform you that you are currently not able to merge your changes into the main branch due to restrictions applied by our SRE team. To proceed with merging your changes, we kindly request that you create a pull request from the development branch. Our team will then review the changes and work with you to ensure a successful merge into the main branch.
       - name: Check branch
         if: github.base_ref == 'main' && github.head_ref != 'staging'
         run: |
-          echo "ERROR: We regret to inform you that you are currently not able to merge your changes into the main branch due to restrictions applied by our SRE team. To proceed with merging your changes, we kindly request that you create a pull request from the next branch. Our team will then review the changes and work with you to ensure a successful merge into the main branch."
+          echo "ERROR: We regret to inform you that you are currently not able to merge your changes into the main branch due to restrictions applied by our SRE team. To proceed with merging your changes, we kindly request that you create a pull request from the development branch. Our team will then review the changes and work with you to ensure a successful merge into the main branch."
+          exit 1
+      - name: Comment PR for staging
+        if: github.base_ref == 'staging' && github.head_ref != 'development'
+        uses: thollander/actions-comment-pull-request@v2
+        with:
+          message: |
+            We regret to inform you that you are currently not able to merge your changes into the staging branch due to restrictions applied by our SRE team. To proceed with merging your changes, we kindly request that you create a pull request from the development branch. Our team will then review the changes and work with you to ensure a successful merge into the staging branch.
+      - name: Check branch for staging
+        if: github.base_ref == 'staging' && github.head_ref != 'development'
+        run: |
+          echo "ERROR: We regret to inform you that you are currently not able to merge your changes into the staging branch due to restrictions applied by our SRE team. To proceed with merging your changes, we kindly request that you create a pull request from the development branch. Our team will then review the changes and work with you to ensure a successful merge into the staging branch."
           exit 1
